output_dir: data
mode: ranking  # ranking | popular
popular:
  pages: 10
  ps: 20
ranking:
  rid: 0     # 0=全站，分区参考B站文档
  day: 3     # 1 | 3 | 7
http:
  timeout: 15
  retry: 3
  backoff: 1.5
  proxy: ""   # 如需：http://127.0.0.1:7890
headers:
  Cookie: "buvid3=9331AF84-9AE8-0DAE-068D-0D100DE1350646905infoc; b_nut=1749122446; _uuid=F26DB1F2-245B-F31E-10104A-F6DE4B410D45445796infoc; buvid_fp=15f3e66b4682851c6df4b1e26cb3d068; buvid4=7AD7F19F-B8ED-9B8C-8AE8-E1E46AE1F82149811-025060519-6rKbHpTBLpUXXhEpQe+HCN91hf1CFLZcWJivmyPf2LwOxPQ5gU5jxeCHSYoebzSl; rpdid=0zbfAHJrAC|14TrZ69AK|2m|3w1Un8Gk; CURRENT_QUALITY=0; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjMxNzY3NjcsImlhdCI6MTc2MjkxNzUwNywicGx0IjotMX0.X3PRNyS2e7DOI5fDT19H-R4X1NWGUBUUUqWnSc7enx8; bili_ticket_expires=1763176707; SESSDATA=0c668b51%2C1778469599%2C980c7%2Ab2CjCD9hX0l5sXUlF7-Z0pxVuVcm9gE2fZzIx0fhnfm2unZXqRwxJRhyzthtmzI6VyQVESVnVrajAwZkJ0MHI4SkZHbi14SE02SGFic2Q1b1l4OXVzeWRNc2d3ZDloVXUtTkVXQUNLOHU0N08yNDJOdzhMbXVsVzkyRG1Jc0I3Z3l1Z0dXNE9OMEhRIIEC; bili_jct=e5aa47d9a3be6525da782dbff8a62153; DedeUserID=1326071639; DedeUserID__ckMd5=09d8d90183a72f5b; CURRENT_FNVAL=2000; theme-tip-show=SHOWED; b_lsid=107657A46_19A766F2B75; bsource=search_google; sid=4qa65aji; home_feed_column=4; browser_resolution=827-773"
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  Referer: "https://www.bilibili.com/"
  Origin: "https://www.bilibili.com"
